# railway.toml

[build]
  # Set the builder to Python (Railway automatically detects Python)
  builder = "python"

  # Command to install dependencies (uses requirements.txt by default)
  install = "pip install --no-cache-dir --verbose fastapi uvicorn python-dotenv pydantic pydantic-settings tweepy groq beautifulsoup4 wikipedia duckduckgo-search langgraph python-multipart httpx requests"

[run]
  # Command to run the application
  command = "uvicorn app:app --host 0.0.0.0 --port 8000"
